packages:
  - apps/*
  - packages/*

allowBuilds:
  '@compodoc/compodoc': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  cbor-extract: true
  cpu-features: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  pkcs11js: true
  protobufjs: true
  sharp: true
  sqlite3: true
  ssh2: true
  workerd: true

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - cbor-extract
  - cpu-features
  - esbuild
  - lmdb
  - msgpackr-extract
  - pkcs11js
  - protobufjs
  - sharp
  - sqlite3
  - ssh2
  - workerd

syncInjectedDepsAfterScripts:
  - build
