import React, {type ReactNode} from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import {DocSearch} from '@docsearch/core';
import {DocSearchAskAiModal} from '@docsearch/modal';
import {Sidepanel} from '@docsearch/sidepanel';

import '@docsearch/css';
import '@docsearch/css/dist/sidepanel.css';

// Ask AI runs on a cost-effective model, so answers may be less reliable than
// a full-size model — let users know before they trust the response.
const ASK_AI_DISCLAIMER =
  'Answers are generated by a lightweight AI model to keep this free service running, and may be inaccurate. Always verify against the docs.';

// Wraps the whole site so DocSearch's Ask AI modal and sidepanel (rendered by
// src/theme/SearchBar) share the same DocSearch provider context.
export default function Root({children}: {children: ReactNode}): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  const {appId, apiKey, indices, agentId} =
    (siteConfig.themeConfig as any).docSearchAskAi ?? {};

  return (
    <BrowserOnly fallback={<>{children}</>}>
      {() => (
        <DocSearch appId={appId} apiKey={apiKey}>
          {children}
          <DocSearchAskAiModal
            indices={indices}
            askAi={{agentId}}
            translations={{
              askAiScreen: {disclaimerText: ASK_AI_DISCLAIMER},
            }}
          />
          <Sidepanel
            agentId={agentId}
            translations={{
              conversationScreen: {conversationDisclaimer: ASK_AI_DISCLAIMER},
              promptForm: {promptDisclaimerText: ASK_AI_DISCLAIMER},
            }}
          />
        </DocSearch>
      )}
    </BrowserOnly>
  );
}
