import { CredentialConfigCreate } from '@eudiplo/sdk-core';

export interface PredefinedConfig {
  name: string;
  description: string;
  icon: string;
  config: CredentialConfigCreate;
}

export const configs: PredefinedConfig[] = [
  {
    name: 'PID (Personal Identity Document)',
    description: 'German Personal Identity Document configuration',
    icon: 'badge',
    config: {
      id: 'pid',
      description: 'Personal ID',
      configVersion: 2,
      config: {
        format: 'dc+sd-jwt',
        scope: 'pid',
        display: [
          {
            name: 'PID',
            description: 'PID Credential',
            locale: 'en-US',
            background_color: '#FFFFFF',
            text_color: '#000000',
          },
        ],
      },
      fields: [
        {
          path: ['issuing_country'],
          type: 'string',
          defaultValue: 'DE',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Issuing Country' }],
        },
        {
          path: ['issuing_authority'],
          type: 'string',
          defaultValue: 'DE',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Issuing Authority' }],
        },
        {
          path: ['given_name'],
          type: 'string',
          defaultValue: 'ERIKA',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Given Name' }],
        },
        {
          path: ['family_name'],
          type: 'string',
          defaultValue: 'MUSTERMANN',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Family Name' }],
        },
        {
          path: ['birth_family_name'],
          type: 'string',
          defaultValue: 'GABLER',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Birth Family Name' }],
        },
        {
          path: ['birthdate'],
          type: 'date',
          defaultValue: '1964-08-12',
          mandatory: true,
          disclosable: true,
          constraints: { pattern: '^\\d{4}-\\d{2}-\\d{2}$' },
          display: [{ locale: 'en-US', name: 'Birthdate' }],
        },
        {
          path: ['age_birth_year'],
          type: 'integer',
          defaultValue: 1964,
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Birth Year' }],
        },
        {
          path: ['age_in_years'],
          type: 'integer',
          defaultValue: 59,
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Age in Years' }],
        },
        {
          path: ['age_equal_or_over'],
          type: 'object',
          defaultValue: {
            '12': true,
            '14': true,
            '16': true,
            '18': true,
            '21': true,
            '65': false,
          },
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Age Equal or Over' }],
        },
        { path: ['age_equal_or_over', '12'], type: 'boolean', defaultValue: true, mandatory: true },
        { path: ['age_equal_or_over', '14'], type: 'boolean', defaultValue: true, mandatory: true },
        { path: ['age_equal_or_over', '16'], type: 'boolean', defaultValue: true, mandatory: true },
        { path: ['age_equal_or_over', '18'], type: 'boolean', defaultValue: true, mandatory: true },
        { path: ['age_equal_or_over', '21'], type: 'boolean', defaultValue: true, mandatory: true },
        {
          path: ['age_equal_or_over', '65'],
          type: 'boolean',
          defaultValue: false,
          mandatory: true,
        },
        {
          path: ['place_of_birth'],
          type: 'object',
          defaultValue: { locality: 'BERLIN' },
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Place of Birth' }],
        },
        {
          path: ['place_of_birth', 'locality'],
          type: 'string',
          defaultValue: 'BERLIN',
          mandatory: true,
          display: [{ locale: 'en-US', name: 'Locality' }],
        },
        {
          path: ['address'],
          type: 'object',
          defaultValue: {
            locality: 'KÖLN',
            postal_code: '51147',
            street_address: 'HEIDESTRAẞE 17',
          },
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Address' }],
        },
        {
          path: ['address', 'locality'],
          type: 'string',
          defaultValue: 'KÖLN',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Locality' }],
        },
        {
          path: ['address', 'postal_code'],
          type: 'string',
          defaultValue: '51147',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Postal Code' }],
        },
        {
          path: ['address', 'street_address'],
          type: 'string',
          defaultValue: 'HEIDESTRAẞE 17',
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Street Address' }],
        },
        {
          path: ['nationalities'],
          type: 'array',
          defaultValue: ['DE'],
          mandatory: true,
          disclosable: true,
          display: [{ locale: 'en-US', name: 'Nationalities' }],
        },
      ],
      vct: {
        name: 'PID',
        description: 'PID credential',
      },
      keyBinding: true,
      keyChainId: '139af178-3ca0-48f4-a2e4-7b1209f30374',
      statusManagement: true,
      lifeTime: 604800,
    },
  },
];
